name: EasyVoteListener
version: 1.4.0
author: bittiez
main: US.bittiez.EasyVoteListener.main
depend: [Votifier]
commands:
    EVL:
        description: EVL Command
        usage: /EVL
        permission: EVL
permissions:
    EVL.test:
        description: Allows the use /EVL test to test your permissions/rewards
        default: op
    EVL.updates:
        description: Will be informed of updates to the plugin
        default: op
    EVL.reload:
        description: Allows the use of /EVL reload to reload the config file
        default: op